ssh_key_anchor: &add_ssh_keys
    fingerprints:
      - "5b:1a:88:80:1f:03:34:b9:b8:67:d2:73:d6:22:a1:98"

version: 2
jobs:
  build:
    branches:
      ignore:
        gh-pages

    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
      - GH_EMAIL: "jadx-ci@circleci"
      - GH_NAME: "Jadx CI - Circleci"
    docker:
      - image: ubuntu:18.04
    steps:
      - add_ssh_keys: *add_ssh_keys
      - checkout
      - run:
          command: |
            apt-get update -qq
            apt-get install -yqq cmake zlib1g-dev python-dev build-essential git software-properties-common
            apt-get install -yqq libpython3.6 libpython3.6-dev python3.6 python3-pip
            apt-get install -yqq g++
            apt-get install -yqq openjdk-8-jdk git
            apt-get update -qq
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            python3.6 -m pip install setuptools --upgrade
            python3.6 -m pip install wheel
            python3.6 -m pip install alabaster Pygments imagesize sphinx sphinx-paramlinks sphinx_rtd_theme
      - run:
          command: |
            python3.6 ./setup.py install --user
            python3.6 ./setup.py build_sphinx
            python3.6 ./setup.py bdist_wheel
            python3.6 ./examples/jadx_decompile.py ./examples/com.passwordchecker.apk --classes com.example.passwordchecker.PasswordChecker
      - deploy:
          name: Deploy Documentation
          branch: master
          command: |
            chmod u+x ./.circleci/deploy-gh-pages.sh
            ./.circleci/deploy-gh-pages.sh





